version: '3'
services:
  database:
    image: "postgres:9.6-alpine"
    ports:
      - "5432:5432" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - ./database/:/var/lib/postgresql/data/

  api:
    restart: always
    container_name: api
    build: './'
    ports:
      - "3333:3333"
    depends_on: 
      - database
    links:
      - database

  