version: '3'
services:
  database:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    env_file:
      - database.env # configure postgres
    volumes:
      - ${HOME}/dev/postgres-data/:/var/lib/postgresql/data/

  api:
    restart: always
    container_name: api
    build: '.'
    ports:
      - 3333:3333
    depends_on:
      - database
    links:
      - database

